language: cpp
os: linux
dist: focal

compiler: gcc

jobs:
  include:
    - language: python
      python: "3.7"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      install:
        - pip3 install -r docs/requirements.txt
      script:
        - mkdir -p ${TRAVIS_BUILD_DIR}/build
        - cd ${TRAVIS_BUILD_DIR}/build
        - cmake ..
        - make -i docs
        - cd ${TRAVIS_BUILD_DIR}
      deploy:
        strategy: git
        provider: pages
        local_dir: ./build/docs/sphinx
        token: $KASIMIR_GH_TOKEN
        verbose: true
        skip_cleanup: true
        cleanup: false
    - before_script:
        - mkdir -p ${TRAVIS_BUILD_DIR}/build-test
        - cd ${TRAVIS_BUILD_DIR}/build-test
        - cmake ..
      script:
        - make -j 8
        - make test
