language: cpp
os: linux
dist: focal
compiler: gcc
jobs:
  include:
  - before_script:
    - mkdir -p ${TRAVIS_BUILD_DIR}/build-test
    - cd ${TRAVIS_BUILD_DIR}/build-test
    - cmake ..
    script:
    - make -j 8
    - make test
